### ISSUE TITLE
cliffsnotes is broken

### ISSUE THREAD

**Issue by dominik-schwabe** [manestay/novel-chapter-dataset#1]
https://github.com/manestay/novel-chapter-dataset/blob/4c4e3a8dd0c3ef08e14e251ead5e82f5ea62d9a7/scraping/cliffsnotes_scrape.py#L24
The link to the books list shows only the books starting with 'A'. Therefore a lot of books are not scraped.
For me the link `https://www.cliffsnotes.com/literature%3Ffilter=ShowAll&sort=TITLE` (the `?` is replaced with `%3F`) worked instead.

**Comment by manestay** [comment]
Hi dominik-schwabe, just seeing this issue now. You're right, the link was out-of-date. I've added a new commit with your fix -- really appreciate it!

**Comment by manestay** [comment]
It seems CliffsNotes updated their site, so that the correct link is now `https://www.cliffsnotes.com/literature?filter=ShowAll&sort=TITLE`, and the `%3F` doesn't work anymore. I will update this in a commit soon.
