### ISSUE TITLE
Code for Alignment

### ISSUE THREAD

**Issue by saxenarohit** [manestay/novel-chapter-dataset#4]
Hi, 

Thanks for sharing the repo of the dataset. I wanted to compare the alignment method used in the paper based on Stable Matching for my work. Will it be possible for you to share the code?

Thanks!

**Comment by manestay** [comment]
Hi @saxenarohit, unfortunately we no longer have have access to the stabled matched alignments we used in this paper. We would suggest taking a look at 

https://github.com/salesforce/booksum (Kryściński et al 2021): these authors collected a larger dataset, and also used our stable matching method. I think they provided the alignment scripts in that repo.
https://github.com/fladhak/creative-summ-data (Agrawal et al 2022): the Creative Summarization workshop was jointly organized by our team, the team for BookSum, and others. The datasets here are more up-to-date, and you could try running the alignment scripts from BookSum on this one.

Tagging my co-author @fladhak in case he has any other information.

**Comment by saxenarohit** [comment]
Thanks @manestay for the pointers.
I can see booksum uses Matching package (https://github.com/daffidwilde/matching) for stable matching. This should work fine. Thanks for your help.

**Comment by manestay** [comment]
Glad I could help!
